### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by KevM** [DarthFubuMVC/fubucore#98]
I tried to add a test and work on a PR but could not because the build would not work. Here is what I tried to do. 

- Clone repo
- git checkout master
- Install Ruby
- `gem install bundler`
- `bundle install`
- `rake` Failed because nugets were missing. 
- `ripple update` - failed with error below

```
>fubucore [master ≡ +0 ~1 -0 !]> ripple update
Updating dependencies for solution fubucore
* Analyzing NUnit,Fixed
Warning: This operation requires NUnit to be updated to 3.0.0 but it is marked as fixed. Use the forceoption to correct this.
* Analyzing RhinoMocks,Fixed
Warning: This operation requires RhinoMocks to be updated to 4.0.0-alpha3 but it is marked as fixed. Use the force option to correct this.
ripple: Could not find RhinoMocks
ripple: Error executing NugetOperation
```

Looks like there is a Nuget version constraint problem on NUnit and/or RhinoMocks.

## Side problem 

Looked to readme for help: 
- https://github.com/DarthFubuMVC/fubucore/blob/master/readme.markdown
- was sent here https://github.com/DarthFubuMVC/fuburake/wiki/README
- Found "Write stuff here" 
- Then I remembered I should `ripple update`

**Comment by jeremydmiller** [comment]
@KevM I don't think you should be needing to do a ripple update. Just `ripple restore`, and that should be called by the rake script.

Look, I think you probably know that FubuCore is essentially a dead project and most of it won't make it into the Jasper ecosystem. If you really need to work with it, I'd actually advise you to convert the build to using Paket instead of Ripple and ditch FubuRake altogether.

**Comment by KevM** [comment]
@jeremydmiller Thanks. I clearly have a terrible memory. I've typed `ripple restore` too many times in the past. 

We are using the `ISettingsProvider` to do conventional configuration settings. Do you know if that will make it into [Jasper](https://github.com/JasperFx/jasper)?
